version: '3.8'

services:
  db-vk:
    image: postgres:15
    container_name: vk-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vkontakte
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data        
      - ./_postgres/:/docker-entrypoint-initdb.d/     

volumes:
  postgres_data: